### ISSUE TITLE
Feature requests & bugs

### ISSUE THREAD

**Issue by ifly-leonard** [Mr-G-D/meeting-recorder#1]
If the page is changed while recording is happening, the recording is lost. 

Feature # 1: we should either hide the options to change page during recording. 

Feature # 2: Options to change timer while recording is happening 

Bug # 1: Unable to find recordings in Ubuntu

**Comment by Mr-G-D** [comment]
@ifly-leonard 
The bugs are fixed. You sir are good to go.

**Comment by ifly-leonard** [comment]
Copied. Thank you, let me check
